version: "3.4"
services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    restart: unless-stopped
    networks:
      - the-promised-land
    environment:
      POSTGRES_DB: the-promised-land
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:

networks:
  the-promised-land:
