# fly.toml app configuration file generated for atp on 2023-07-03T22:52:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "atp"
primary_region = "gru"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  FLY_LAUNCH_MODE = "clone"
  PHX_HOST = "simbolismodigital.com.br"
  VIRTUAL_HOST = "simbolismodigital.com.br"
  PORT = "8080"
  EXTERNAL_IP = "149.248.198.18"
  INTEGRATED_TURN_IP = "149.248.198.18"
  INTEGRATED_TCP_TURN_PORT = "3478"
  INTEGRATED_TURN_PORT_RANGE = "50000-59999"
  INTEGRATED_TURN_LISTEN_IP = "fly-global-services"
  WEBRTC_USED = "true"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[services]]
  internal_port = 50000
  protocol = "udp"

  [[services.ports]]
    port = 50000